In [1]:
import numpy as np


In [7]:
a = np.array([1,2,3,4])
b = np.array([0.5,0.5,0.75,1.])
theta_vecs = np.linspace(a-b,a+b,3)
theta_vecs

array([[0.5 , 1.5 , 2.25, 3.  ],
       [1.  , 2.  , 3.  , 4.  ],
       [1.5 , 2.5 , 3.75, 5.  ]])

In [23]:
theta_vecs.shape

(3, 4)

In [15]:
lnp0 = - (theta_vecs[:,0] - a[0])**2/(2*b[0]**2)
lnp0

array([-0.5, -0. , -0.5])

In [24]:
theta_vecs + lnp0[:,None]

array([[0.  , 1.  , 1.75, 2.5 ],
       [1.  , 2.  , 3.  , 4.  ],
       [1.  , 2.  , 3.25, 4.5 ]])

In [22]:
np.atleast_1d(np.array([1,2]))[0]

1